version: '3'
services:
  api:
    build: ./api
    command: nodemon ./src/index.js
    ports:
      - "8080:3000"
    volumes:
      - ./api/:/app/api/
    links:
      - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=dev 
    ports:
      - "27018:27017"